global:
  edition: ce
  hosts:
    domain: centos.local
    externalIP: 10.0.0.2
    https: false
  ingress:
    configureCertmanager: false
    class: "nginx"
    tls:
      enabled: false
  time_zone: "Asia/Shanghai"
  appConfig:
    time_zone: "Asia/Shanghai"
certmanager:
  install: false
nginx-ingress:
  enabled: false
prometheus:
  install: false
redis-ha:
  enabled: false
gitlab-runner:
  install: false
gitlab:
  gitaly:
    persistence:
      size: 5Gi
  unicorn:
    minReplicas: 1
    maxReplicas: 1
    #    resources:
    #      limits:
    #        cpu: 500m
    #        memory: 512Mi
    #      requests:
    #        cpu: 50m
    #        memory: 64Mi
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
    #    resources:
    #      requests:
    #        cpu: 50m
    #        memory: 64M
    #      limits:
    #        cpu: 500m
    #        memory: 512M
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
  task-runner:
    #    resources:
    #      requests:
    #        cpu: 50m
    #        memory: 64M
    #      limits:
    #        cpu: 500m
    #        memory: 512M
    persistence:
      size: 2Gi
registry:
  minReplicas: 1
  maxReplicas: 1
postgresql:
  persistence:
    size: 2Gi
redis:
  persistence:
    size: 1Gi
minio:
  persistence:
    size: 2Gi
