apiVersion: v1
kind: Pod
metadata:
  name: multiple-image
spec:
  containers:
    - name: 1st
      image: ubuntu
      tty: true
      #command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
      command: ["cat"]
    - name: 2nd
      image: centos
      tty: true
      command: ["cat"]
  restartPolicy: Never
