master:
  adminPassword: "admin"
  resources:
    limits:
      cpu: "1000m"
      memory: "1024Mi"
  serviceType: ClusterIP
  installPlugins:
    - kubernetes:1.18.1
    - workflow-job:2.33
    - workflow-aggregator:2.6
    - credentials-binding:1.19
    - git:3.12.0
    - GitLab:1.5.12
  ingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1beta1"
    annotations:
      kubernetes.io/ingress.class: nginx
    hostName: jenkins.centos.local
agent:
  alwaysPullImage: true
persistence:
  size: "2Gi"
