imageTag: latest
mysqlRootPassword: root
imagePullPolicy: Always
persistence:
  size: 1Gi
resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m
timezone: 'Asia/Shanghai'
