image: mysql
imagePullPolicy: Always
imageTag: latest
mysqlRootPassword: root
persistence:
  accessMode: ReadWriteOnce
  enabled: true
  size: 1Gi
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
